# Generated by Django 3.1.7 on 2021-04-06 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_data',
            name='Branches',
        ),
        migrations.DeleteModel(
            name='Branches',
        ),
    ]
