# Generated by Django 3.1.7 on 2021-04-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_auto_20210406_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10),
        ),
    ]
