# Generated by Django 3.1.7 on 2021-04-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0003_auto_20210406_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='selection',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='FEMALE', max_length=15),
        ),
    ]
