# Generated by Django 3.1.7 on 2021-04-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0004_student_data_selection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_data',
            name='selection',
        ),
    ]
