# Generated by Django 3.1.7 on 2021-04-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0005_remove_student_data_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6),
        ),
    ]
