# Generated by Django 3.2 on 2021-04-06 11:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Branch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Data',
            new_name='Stu_Data',
        ),
    ]
