# Generated by Django 3.1.7 on 2021-04-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0002_rename_student_data_stu_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='branch',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='stu_data',
            name='country',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='stu_data',
            name='gender',
            field=models.CharField(max_length=7),
        ),
    ]
