# Generated by Django 3.1.7 on 2021-04-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0003_auto_20210406_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_data',
            name='User',
        ),
    ]
