# Generated by Django 3.1.7 on 2021-04-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0004_remove_stu_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_data',
            name='password',
        ),
    ]
