# Generated by Django 3.1.7 on 2021-04-07 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0007_remove_branches_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_data',
            name='Branches',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Branch.branches'),
        ),
    ]
